from __future__ import annotations


SOURCE = "Language Coach 原创审核例句（v0.8.0-alpha.25.11）"


def item(pos, meaning_zh, focus_en, focus, patterns, register, avoid, example, example_zh):
    return {
        "pos": pos,
        "meaning_zh": meaning_zh,
        "focus_en": focus_en,
        "focus": focus,
        "patterns": patterns,
        "register": register,
        "avoid": avoid,
        "example": example,
        "example_zh": example_zh,
        "example_source": SOURCE,
    }


def comparison(slug, terms, shared_translation, summary, memory_rule, dimensions, items):
    return {
        "slug": slug,
        "terms": terms,
        "title": " / ".join(terms),
        "shared_translation": shared_translation,
        "summary": summary,
        "memory_rule": memory_rule,
        "dimensions": [{"label": label, "value": value} for label, value in dimensions],
        "items": items,
        "confusion_type": "semantic",
        "exam_tags": ["IELTS"],
        "topic": "charts",
    }


IELTS_CHART_CURATED_COMPARISONS = (
    comparison(
        "ielts-increase-grow-expand", ("increase", "grow", "expand"),
        "都可能表示增加，但数值变化、自然发展和范围扩大不是同一个视角。",
        "increase 是最中性的数量或程度上升；grow 常暗示随时间发展；expand 强调尺寸、容量、范围或业务版图变大。",
        "数值升高用 increase，发展壮大用 grow，边界向外扩大用 expand。",
        (("变化对象", "increase 接数值、数量或程度；grow 常接人口、经济和需求；expand 常接面积、容量、范围和业务。"),
         ("句法", "三者均可不及物；increase 和 expand 也常及物，grow 及物时多表示种植或使逐渐形成。"),
         ("图表安全性", "只描述数据上升时 increase 最稳妥；不要为追求同义替换而把所有 rise 改成 expand。")),
        {
            "increase": item("verb/noun", "增加；增长", "become or make greater in amount, number, or degree", "中性描述可测量数值或程度变大。", ["increase from A to B", "an increase of 20%"], "中性、正式，图表写作最通用。", "increase by 20% 表示增幅，increase to 20% 表示终值，不能混用。", "The proportion increased from 28% to 41% over the period.", "这一比例在该时期从 28% 上升到 41%。"),
            "grow": item("verb", "增长；发展", "develop and become larger over time", "强调随时间发展形成的增长过程。", ["grow steadily", "grow to 2 million"], "中性；人口、经济、市场和需求语境自然。", "通常不用 grow 描述一次机械调整后的单个比例点。", "Demand for rail travel grew steadily after 2015.", "2015 年后，铁路出行需求稳步增长。"),
            "expand": item("verb", "扩大；扩展", "become or make larger in size, scope, capacity, or range", "突出边界、覆盖范围或容量向外扩展。", ["expand its capacity", "expand into new markets"], "中性偏正式；适合业务、设施和范围。", "一个百分比单纯变高通常不用 expand。", "The airport expanded its passenger capacity during the decade.", "该机场在这十年间扩大了客运容量。"),
        },
    ),
    comparison(
        "ielts-decrease-decline-drop", ("decrease", "decline", "drop"),
        "都可译为下降，但中性变化、持续走弱和明显下落的语气不同。",
        "decrease 是中性统计词；decline 常呈现一段时间的走弱；drop 更直接，常暗示较快或明显下降。",
        "中性数值用 decrease，持续走弱用 decline，明显下落用 drop。",
        (("语气", "decrease 最中性；decline 较正式且常有负面趋势；drop 更口语化、视觉感更强。"),
         ("句法", "三者均可作动词或名词，但 decrease 可及物；decline/drop 在图表义中多不及物。"),
         ("幅度", "词本身不能代替幅度数据；a slight drop 和 a sharp decline 都需由图表支持。")),
        {
            "decrease": item("verb/noun", "减少；下降", "become or make smaller in amount, number, or degree", "对数值减少作中性、可量化描述。", ["decrease by 12%", "a decrease in costs"], "正式、中性，图表写作安全。", "不要混淆 decrease by（减少量）与 decrease to（降至终值）。", "Average household spending decreased by 12% in the final year.", "最后一年，家庭平均支出下降了 12%。"),
            "decline": item("verb/noun", "下降；衰退", "become lower, weaker, or less over a period", "常把下降呈现为一段持续走弱的趋势。", ["decline gradually", "a decline in employment"], "中性偏正式；经济、健康和参与度中常见。", "decline 还可表示拒绝，图表中要靠搭配明确其下降义。", "Employment in manufacturing declined gradually after 2010.", "2010 年后，制造业就业人数逐渐下降。"),
            "drop": item("verb/noun", "下降；下跌", "fall to a lower level, often noticeably or quickly", "强调数值向下移动，常带明显或突然的感觉。", ["drop sharply", "a drop of 15 points"], "中性偏口语，但图表报告中很常见。", "数据缓慢微降时不要自动写 plummet 或 dramatic drop。", "The figure dropped sharply to 36% in 2020.", "该数据在 2020 年急剧降至 36%。"),
        },
    ),
    comparison(
        "ielts-fluctuate-oscillate", ("fluctuate", "oscillate"),
        "都涉及上下变化，但不规则波动和在两端之间往返不同。",
        "fluctuate 描述数值不规则升降；oscillate 更技术化，强调在两个值、状态或方向之间反复摆动。",
        "不规则上下是 fluctuate，两端往返是 oscillate。",
        (("路径", "fluctuate 可有多个高低点；oscillate 通常围绕范围或在两个端点之间反复。"),
         ("语域", "fluctuate 是常规图表词；oscillate 更技术化，需图形确有周期或两端往返。"),
         ("搭配", "figures fluctuate between A and B；a value oscillates around/between levels。")),
        {
            "fluctuate": item("verb", "波动；起伏", "rise and fall irregularly in level or amount", "表示数据在一段时期内多次、不规则地升降。", ["fluctuate between A and B", "fluctuate slightly"], "正式、中性，图表高频。", "只有一次上升后下降不一定构成 fluctuate。", "Oil prices fluctuated between $60 and $75 per barrel.", "油价在每桶 60 至 75 美元之间波动。"),
            "oscillate": item("verb", "振荡；在两者间反复变化", "move repeatedly between two points, values, or states", "突出围绕中心或在两个端点之间反复往返。", ["oscillate between two levels", "oscillate around the mean"], "技术和学术语域较强。", "普通的不规则数据起伏优先用 fluctuate，避免无依据地暗示周期性。", "The reading oscillated around the long-term mean.", "该读数围绕长期平均值上下振荡。"),
        },
    ),
    comparison(
        "ielts-stable-steady-constant", ("stable", "steady", "constant"),
        "都可译为稳定，但容许小幅变化、变化速度一致和完全不变的标准不同。",
        "stable 表示没有重大波动；steady 表示水平或变化速率持续一致；constant 表示数值或条件保持不变。",
        "大体不乱是 stable，节奏一致是 steady，数值不变才是 constant。",
        (("容差", "stable 可容许小波动；steady 可描述稳定水平或匀速变化；constant 通常不容许变化。"),
         ("搭配", "remain stable；a steady rise；remain constant at 40%。"),
         ("图表判断", "持续匀速上升可称 steady increase，却不能称数值 stable 或 constant。")),
        {
            "stable": item("adjective", "稳定的", "not changing greatly or becoming uncontrolled", "强调没有显著波动或失控，可有轻微变化。", ["remain relatively stable", "a stable level"], "中性、正式，图表高频。", "有持续明显上升的曲线不能只因平滑就称 stable。", "The unemployment rate remained relatively stable at around 5%.", "失业率保持相对稳定，约为 5%。"),
            "steady": item("adjective", "平稳的；持续的", "continuing at a consistent level, pace, or rate", "强调水平、速度或方向持续一致。", ["a steady increase", "hold steady at"], "中性、正式。", "steady rise 表示稳定地上升，不表示数值不变。", "The chart shows a steady rise in online enrolments.", "图表显示在线注册人数稳步上升。"),
            "constant": item("adjective/noun", "恒定的；常数", "remaining exactly or essentially unchanged", "强调某个数值、条件或频率持续不变。", ["remain constant at", "at a constant rate"], "正式，科学和统计语境常见。", "若图中存在可见波动，通常不要写 remained constant。", "The tax rate remained constant at 18% throughout the period.", "整个时期税率一直保持在 18%。"),
        },
    ),
    comparison(
        "ielts-slight-marginal-modest", ("slight", "marginal", "modest"),
        "都可表示幅度小，但普通小幅、接近边缘和有限但可见的评价不同。",
        "slight 是最普通的小幅；marginal 强调差异很小、接近无关紧要；modest 表示有限、不大但通常仍值得注意。",
        "小幅用 slight，小到边缘用 marginal，有限但可见用 modest。",
        (("程度", "slight 只说小；marginal 常暗示刚超过边界或影响有限；modest 比 dramatic 克制但不等于可忽略。"),
         ("搭配", "a slight fall；a marginal difference；a modest increase。"),
         ("立场", "marginal/modest 含有评价色彩，必须与实际尺度和任务语境一致。")),
        {
            "slight": item("adjective", "轻微的；小幅的", "small in degree or amount", "对变化幅度作普通、较少带评价的描述。", ["a slight increase", "a slight difference"], "中性，图表高频。", "明显变化不能仅为了语气克制写 slight。", "There was a slight fall in bus use during the summer.", "夏季公交使用量略有下降。"),
            "marginal": item("adjective", "微小的；边际的", "very small or close to a limit of significance", "强调差异接近边缘、实际影响可能有限。", ["a marginal rise", "a marginal difference"], "正式；统计、经济和评估语境常见。", "marginal 还有边缘化、边际的专业义，不是 slight 的万能替换。", "The second group recorded only a marginal improvement.", "第二组仅取得了极小的改善。"),
            "modest": item("adjective", "适度的；有限的", "limited in size but still noticeable or respectable", "表示幅度不大，通常仍可观察或具有一定意义。", ["a modest increase", "modest growth"], "中性偏正式，常带克制评价。", "modest 也可形容人谦虚；图表中需与 increase/growth 等搭配。", "Exports showed a modest increase of 6%.", "出口额出现了 6% 的温和增长。"),
        },
    ),
    comparison(
        "ielts-sharp-steep-dramatic", ("sharp", "steep", "dramatic"),
        "都可描述大幅变化，但突然清晰、坡度大和视觉冲击强的焦点不同。",
        "sharp 强调快速且明显；steep 强调短时间内幅度很大、曲线坡度陡；dramatic 强调变化显著而引人注目。",
        "快而明显是 sharp，坡度陡是 steep，冲击强是 dramatic。",
        (("时间与幅度", "sharp 常兼顾速度和清晰度；steep 强调单位时间内的大幅变化；dramatic 强调总体显著性。"),
         ("搭配", "a sharp drop；a steep rise；a dramatic change。"),
         ("证据", "三个词都不能替代数字；曲线变化普通时应使用 marked/significant 或直接报告数值。")),
        {
            "sharp": item("adjective", "急剧的；明显的", "sudden and clearly noticeable", "常描述短时间内清晰可见的上升或下降。", ["a sharp increase", "fall sharply"], "中性偏正式，图表高频。", "sharp 还可表示锋利、敏锐；不要忽略上下文。", "A sharp decline occurred between 2018 and 2019.", "2018 至 2019 年间出现了急剧下降。"),
            "steep": item("adjective", "陡峭的；大幅而迅速的", "changing by a large amount over a short interval", "借用坡度概念，突出曲线在短区间内大幅变化。", ["a steep rise", "a steep decline"], "中性偏正式。", "steep 通常修饰变化或价格，不直接把任意高数值称为 steep。", "The graph records a steep rise in housing costs after 2022.", "图表显示 2022 年后住房成本大幅攀升。"),
            "dramatic": item("adjective", "显著而惊人的；剧烈的", "large, striking, and attention-grabbing", "强调变化给观察者的强烈总体印象。", ["a dramatic change", "increase dramatically"], "有评价色彩，正式报告中应谨慎。", "不要把任何超过 10% 的变化机械称为 dramatic；需结合比例尺和背景。", "The final decade brought a dramatic shift towards renewable energy.", "最后十年出现了向可再生能源的显著转变。"),
        },
    ),
    comparison(
        "ielts-proportion-percentage-rate-ratio", ("proportion", "percentage", "rate", "ratio"),
        "中文都可能译成比例或比率，但整体份额、百分表示、单位发生率和两量之比必须区分。",
        "proportion 是部分占整体的份额；percentage 是以 100 为基数的表示；rate 是每单位时间或人群的发生水平；ratio 是两个量的对应关系。",
        "部分/整体是 proportion，乘百写 percentage，每单位是 rate，两量相比是 ratio。",
        (("分母", "proportion 的分母是整体；percentage = proportion × 100%；rate 带时间/人口等暴露单位；ratio 比较两个独立量。"),
         ("形式", "40% is a percentage；2 in 5 is a proportion；5 per 1,000 is a rate；3:2 is a ratio。"),
         ("不可互换", "看到 % 不代表原指标一定叫 rate；ratio 也不自动表示某部分占整体。")),
        {
            "proportion": item("noun", "比例；部分所占份额", "a part considered in relation to the whole", "突出某一部分在整体中的占比。", ["the proportion of households", "a high proportion of"], "正式、中性，Task 1 高频。", "不能把两个互不包含的群体之比直接称为 proportion。", "The proportion of one-person households rose to 32%.", "单人家庭所占比例上升到 32%。"),
            "percentage": item("noun", "百分比", "a proportion expressed as a number out of one hundred", "专指以百分数表达的份额或变化。", ["the percentage of respondents", "a percentage-point increase"], "中性、统计语境。", "从 20% 到 25% 是增加 5 个百分点，也可说增加 25%，二者不同。", "The percentage of graduates in full-time work reached 74%.", "从事全职工作的毕业生比例达到 74%。"),
            "rate": item("noun", "率；速率；比率", "a measure relative to time, population, or another exposure unit", "表示某事件按时间、人口或其他单位计算的发生水平。", ["the unemployment rate", "a rate of 8 per 1,000"], "正式，经济、人口和科学语境高频。", "单纯的群体份额未必是 rate，应先确认指标定义。", "The birth rate fell to 8 per 1,000 residents.", "出生率降至每千名居民 8 人。"),
            "ratio": item("noun", "比；比率", "the quantitative relation between two amounts", "比较两个量的相对大小，常写成 A:B。", ["the ratio of A to B", "a three-to-two ratio"], "正式、数学和统计语境。", "ratio 不要求两项合计为整体，也不等同于 percentage。", "The ratio of urban to rural applicants was three to two.", "城市申请者与农村申请者之比为三比二。"),
        },
    ),
    comparison(
        "ielts-amount-number-quantity", ("amount", "number", "quantity"),
        "都可表示数量，但不可数、可数和正式统称的语法边界不同。",
        "amount 通常修饰不可数名词；number 修饰可数复数；quantity 较正式，可指可数或不可数事物的量。",
        "不可数看 amount，可数复数看 number，正式统称可用 quantity。",
        (("名词类型", "an amount of water；a number of cars；a quantity of goods/water。"),
         ("图表搭配", "the amount of money；the number of visitors；the quantity of waste produced。"),
         ("一致", "the number of students is...；a number of students are...，结构不同。")),
        {
            "amount": item("noun", "数量；总额", "a quantity of something treated as uncountable", "常接金钱、时间、水、能源等不可数概念。", ["the amount of money", "a large amount of waste"], "中性、正式。", "标准正式写作中避免 the amount of people/cars。", "The amount of electricity used by industry fell slightly.", "工业用电量略有下降。"),
            "number": item("noun", "数量；数目", "a count of separate people or things", "用于可以逐个计数的人或事物。", ["the number of visitors", "a growing number of"], "中性、正式，图表高频。", "不要用 number of water/traffic 表示不可数总量。", "The number of international visitors exceeded two million.", "国际游客人数超过了两百万。"),
            "quantity": item("noun", "数量；量", "an amount or number measured as a quantity", "较正式地统称可测量的量，可用于可数或不可数对象。", ["a quantity of goods", "the quantity consumed"], "正式；技术、生产和物流语境常见。", "日常人口统计中 number 往往比 quantity of people 更自然。", "The quantity of recycled material doubled within five years.", "回收材料的数量在五年内翻了一番。"),
        },
    ),
    comparison(
        "ielts-trend-pattern-tendency", ("trend", "pattern", "tendency"),
        "都可与变化规律有关，但长期方向、重复结构和倾向性不同。",
        "trend 是数据随时间的总体方向；pattern 是可重复或可识别的结构；tendency 是较常发生或朝某方向发展的倾向。",
        "时间方向是 trend，重复结构是 pattern，较常如此是 tendency。",
        (("时间", "trend 通常需要时间序列；pattern 可出现在时间、群体或空间分布中；tendency 不一定有完整数据序列。"),
         ("证据强度", "trend/pattern 可直接由图表观察；tendency 常是概括性判断，语气更保留。"),
         ("搭配", "an upward trend；a seasonal pattern；a tendency to increase。")),
        {
            "trend": item("noun", "趋势；走向", "a general direction of change over time", "概括一段时期内数据总体向上、向下或转移的方向。", ["an upward trend", "reverse the trend"], "正式、中性，Task 1 高频。", "单一时间点的差异不能构成 trend。", "The chart reveals a clear downward trend in coal consumption.", "图表显示煤炭消费呈明显下降趋势。"),
            "pattern": item("noun", "模式；规律", "a regular or identifiable arrangement in data or behaviour", "强调数据中重复、成组或可识别的结构。", ["a similar pattern", "a seasonal pattern"], "正式、中性。", "pattern 不必表示持续上升或下降，不要与 trend 机械互换。", "All three cities followed a similar seasonal pattern.", "三个城市都呈现出相似的季节性规律。"),
            "tendency": item("noun", "倾向；趋向", "a likelihood to behave or develop in a particular way", "表示较常出现某种行为或变化方向，但未必是绝对规律。", ["a tendency to rise", "a general tendency"], "正式，语气比固定规律更保留。", "清晰连续的时间序列通常直接称 trend 更准确。", "Smaller firms showed a tendency to invest later.", "规模较小的企业往往较晚投资。"),
        },
    ),
    comparison(
        "ielts-peak-maximum-high", ("peak", "maximum", "high"),
        "都可能指高点，但观测峰值、理论或规定上限和普通高水平不同。",
        "peak 是序列中达到后通常回落的最高点；maximum 是允许、可能或样本中的最大值；high 只是相对较高的水平。",
        "曲线峰顶是 peak，最大界限是 maximum，只是偏高用 high。",
        (("最高性", "peak/maximum 都可指最高点；high 不保证是最高。"),
         ("时间形态", "peak 常隐含先升后降；maximum 可无时间过程；high 可作名词表示阶段高点。"),
         ("句法", "peak at 80；reach a maximum of 80；remain at a high level。")),
        {
            "peak": item("noun/verb", "峰值；达到峰值", "the highest observed point in a changing series", "强调变化序列中的顶点，常与前后走势相连。", ["peak at 80", "reach a peak of 80"], "中性、正式，图表高频。", "若最高值出现在区间末端且没有回落，maximum/highest point 可能更稳妥。", "Passenger numbers peaked at 1.8 million in August.", "客运量在 8 月达到 180 万的峰值。"),
            "maximum": item("noun/adjective", "最大值；最高限度", "the greatest value that is possible, allowed, or observed", "强调数值范围、制度或样本中的最大边界。", ["a maximum of 50", "the maximum value"], "正式，技术和统计语境。", "maximum 本身不表达先升后降的曲线过程。", "The machine operated at a maximum capacity of 500 units per hour.", "该机器以每小时 500 件的最大产能运行。"),
            "high": item("noun/adjective", "高点；高水平的", "a level that is large relative to a reference", "只表示相对较高，可不是整个序列的最高值。", ["remain high", "reach a five-year high"], "中性；five-year high 等表达常见。", "写 a high 时应给出比较范围，如 record high 或 five-year high。", "Demand remained high throughout the winter months.", "整个冬季需求一直处于高位。"),
        },
    ),
)


IELTS_CHART_CURATED_COMPARISONS += (
    comparison(
        "ielts-minimum-lowest-nadir", ("minimum", "lowest", "nadir"),
        "都可能表示最低，但最小界限、实际最低项和带修辞色彩的低谷不同。",
        "minimum 是允许、需要或可能的最小值；lowest 是 low 的最高级，指出比较范围内最低者；nadir 是发展过程中的最低谷，常带负面修辞色彩。",
        "最小界限用 minimum，比较结果用 lowest，负面低谷才用 nadir。",
        (("范围", "minimum 可由规则或数学定义；lowest 必须有比较范围；nadir 常属于历史或表现轨迹。"),
         ("语域", "minimum/lowest 是中性统计词；nadir 正式且修辞性强。"),
         ("句法", "a minimum of 10；the lowest figure；reach its nadir。")),
        {
            "minimum": item("noun/adjective", "最小值；最低限度", "the smallest value that is possible, allowed, or required", "强调范围或规则中的下限。", ["a minimum of 10", "the minimum value"], "正式，统计和规则语境常见。", "minimum 不自动表示某年实际观测值最低。", "The minimum monthly charge was set at $12.", "每月最低收费定为 12 美元。"),
            "lowest": item("adjective", "最低的", "lower than every other value in the stated comparison", "直接指出所比较项目或时间点中的最低值。", ["the lowest figure", "fall to its lowest level"], "中性，图表写作高频。", "需明确比较范围；lowest ever 和 lowest in the period 含义不同。", "The rural region recorded the lowest figure, at 14%.", "农村地区的数据最低，为 14%。"),
            "nadir": item("noun", "最低点；低谷", "the worst or lowest point in a process or history", "强调表现、发展或历史过程中的负面低谷。", ["reach its nadir", "the nadir of the decline"], "正式、修辞性较强。", "普通柱状图的最小值通常用 lowest/minimum，不要为显得高级而用 nadir。", "Public confidence reached its nadir during the recession.", "公众信心在经济衰退期间跌至低谷。"),
        },
    ),
    comparison(
        "ielts-approximately-roughly-about", ("approximately", "roughly", "about"),
        "都表示约数，但正式程度和对精确性的态度不同。",
        "approximately 是正式、中性的近似；roughly 明示粗略估计；about 最自然通用，但正式报告中语气稍弱。",
        "正式近似用 approximately，粗估用 roughly，通用约数用 about。",
        (("正式度", "approximately 最正式；roughly 中性但强调粗略；about 最通用。"),
         ("精度", "三者都不能修复错误读数；约数范围仍应与坐标刻度相称。"),
         ("位置", "approximately/about 50 people；roughly half；数字前通常不再叠加 nearly。")),
        {
            "approximately": item("adverb", "大约；近似地", "close to an exact number but not exact", "以正式、中性的方式给出接近值。", ["approximately 40%", "approximately equal to"], "正式，学术和图表报告首选。", "坐标给出精确标签时不必无故加 approximately。", "Approximately 40% of respondents chose public transport.", "大约 40% 的受访者选择了公共交通。"),
            "roughly": item("adverb", "大致；粗略地", "in an approximate way without fine precision", "强调读数或估计是粗略的。", ["roughly one third", "roughly the same"], "中性；比 approximately 稍不正式。", "需要精确报告的小数或显著差异不应写 roughly。", "The two categories accounted for roughly one third of the total.", "这两个类别约占总数的三分之一。"),
            "about": item("adverb/preposition", "大约；左右", "a little more or less than a stated number", "最通用地表示数字上下略有浮动。", ["about 500 units", "at about the same level"], "中性、自然；正式度略低于 approximately。", "about 不能与精确性声称如 exactly 同时修饰同一数字。", "The figure remained at about 500 units for three years.", "该数据连续三年保持在约 500 个单位。"),
        },
    ),
    comparison(
        "ielts-respectively-correspondingly", ("respectively", "correspondingly"),
        "中文都可能出现“分别、相应地”，但按顺序配对与随另一变化相应改变不同。",
        "respectively 把两组项目按列举顺序一一配对；correspondingly 表示某变化与另一变化相应发生或程度相称。",
        "按顺序配对用 respectively，随之相应变化用 correspondingly。",
        (("逻辑", "respectively 是列表映射；correspondingly 是关联变化或相称关系。"),
         ("位置", "A and B were 10 and 20, respectively；X rose and Y increased correspondingly。"),
         ("必要性", "只有一个项目时不用 respectively；没有对应变化时不用 correspondingly。")),
        {
            "respectively": item("adverb", "分别；各自", "in the same order as the people or things just listed", "按前后两个列表的顺序建立一一对应。", ["A and B were X and Y, respectively", "at 20% and 30%, respectively"], "正式、紧凑，图表写作常见。", "项目与数值顺序不清时不要使用，容易制造错误配对。", "France and Italy recorded 42% and 38%, respectively.", "法国和意大利的数据分别为 42% 和 38%。"),
            "correspondingly": item("adverb", "相应地；随之", "in a matching or directly related way", "说明一项变化伴随另一项相应变化。", ["rise correspondingly", "correspondingly lower"], "正式，使用频率低于 respectively。", "它不负责把两个列表按顺序配对。", "As output increased, unit costs became correspondingly lower.", "随着产量增加，单位成本相应降低。"),
        },
    ),
    comparison(
        "ielts-overall-generally-on-the-whole", ("overall", "generally", "on the whole"),
        "都可用于概括，但总体合计、普遍情况和权衡后的整体判断不同。",
        "overall 从全部数据或全局看；generally 表示多数情况或通常如此；on the whole 在考虑例外后给出整体评价。",
        "全局概览用 overall，多数通常用 generally，权衡例外用 on the whole。",
        (("功能", "overall 常引出 Task 1 overview；generally 概括典型规律；on the whole 常作评价性总结。"),
         ("词性", "overall 可作形容词或副词；generally 是副词；on the whole 是固定介词短语。"),
         ("证据", "overall 不等于 every category；概括时仍要承认明显例外。")),
        {
            "overall": item("adverb/adjective", "总体上；整体的", "considering all parts or the complete picture", "从全部类别、时期或结果提取总览。", ["overall, the figure rose", "the overall trend"], "正式、中性，Task 1 总览高频。", "不要用 overall 引出只涉及一个局部类别的细节。", "Overall, car use rose while cycling became less common.", "总体而言，汽车使用增加，而骑行变得不那么普遍。"),
            "generally": item("adverb", "通常；大体上", "in most cases or as a broad tendency", "说明多数情况符合某规律，但允许例外。", ["generally higher than", "generally follow the same pattern"], "中性、正式。", "它表示普遍性，不一定是在汇总所有数值。", "Prices were generally higher in coastal cities.", "沿海城市的价格通常更高。"),
            "on the whole": item("adverbial phrase", "总的来说；整体看来", "after considering the main facts and exceptions", "在权衡不同方面或例外后作总体判断。", ["on the whole, ...", "perform well on the whole"], "中性偏书面，评价性较强。", "纯数据概览通常 overall 更简洁；不要重复写 overall, on the whole。", "On the whole, the programme produced positive results despite one weak year.", "总的来说，尽管有一年表现不佳，该项目仍取得了积极成果。"),
        },
    ),
    comparison(
        "ielts-remain-stay-maintain", ("remain", "stay", "maintain"),
        "都可涉及保持，但状态延续、较口语的停留和主动维持的句法不同。",
        "remain 和 stay 多为不及物或系动结构，表示状态继续；maintain 是及物动词，表示主体使某水平持续。",
        "状态自己延续用 remain/stay，主体把它维持住用 maintain。",
        (("及物性", "remain/stay + adjective/at level；maintain + object。"),
         ("正式度", "remain 比 stay 更适合正式图表；maintain 强调控制、努力或政策作用。"),
         ("主语", "the rate remained stable；the company maintained the rate。")),
        {
            "remain": item("verb", "保持；仍然是", "continue to be in the same state or at the same level", "正式描述某状态或水平延续。", ["remain stable", "remain at 30%"], "正式、中性，图表首选。", "remain 通常不直接接宾语，不能说 remain the rate at 30%。", "The share remained at 30% until 2018.", "这一份额直到 2018 年都保持在 30%。"),
            "stay": item("verb", "保持；停留", "continue in a state, place, or level", "与 remain 相近，但语气更日常。", ["stay constant", "stay at the same level"], "中性偏日常；图表中可用但不必强行替换 remain。", "stay 也表示居住或停留，需靠补语明确。", "The figure stayed below 10% for most of the period.", "该数据在大部分时期都保持在 10% 以下。"),
            "maintain": item("verb", "维持；保持", "actively keep something at a particular level or condition", "强调主体采取行动使对象维持某状态。", ["maintain a stable rate", "maintain output at"], "正式，管理和政策语境常见。", "图表数值自身不作主动主体时，通常用 remain 而不是 maintain。", "The operator maintained output at 600 units per day.", "运营方将产量维持在每天 600 件。"),
        },
    ),
    comparison(
        "ielts-reach-hit-attain", ("reach", "hit", "attain"),
        "都可表示达到，但中性终点、带冲击感的数值触及和努力实现目标不同。",
        "reach 是最中性的达到数值或阶段；hit 更直接，常用于突然触及高低点；attain 正式强调经过努力达到目标或水平。",
        "中性终值用 reach，突然触点用 hit，努力达成用 attain。",
        (("宾语", "reach/hit 直接接数字或 level；attain 常接 goal, standard, level。"),
         ("语气", "reach 中性；hit 生动且略非正式；attain 正式并带成就过程。"),
         ("介词", "reach 50%，不写 reach to 50%；rise to 50% 才使用 to。")),
        {
            "reach": item("verb", "达到；到达", "arrive at a value, level, stage, or destination", "中性报告某数值或过程到达终点。", ["reach 60%", "reach a peak of"], "中性、正式，图表高频。", "reach 后直接接数值，避免 reach to 60%。", "Internet access reached 90% in the final year.", "最后一年，互联网普及率达到 90%。"),
            "hit": item("verb", "达到；触及", "reach a particular, often striking, level", "带有触及高点、低点或显著数字的直接感。", ["hit a record high", "hit 1 million"], "新闻和商务语境常见，略不正式。", "普通、渐进的终值不必为了变化词汇使用 hit。", "Monthly sales hit a record high in December.", "月销售额在 12 月创下历史新高。"),
            "attain": item("verb", "达到；实现", "succeed in reaching a desired standard, state, or goal", "强调通过发展或努力实现目标水平。", ["attain a target", "attain a high level"], "正式，学术和制度语境。", "单纯读出折线终值时 reach 通常更自然。", "Three regions attained the national recycling target.", "三个地区达到了国家回收目标。"),
        },
    ),
    comparison(
        "ielts-double-multiply-increase-twofold", ("double", "multiply", "increase twofold"),
        "都与倍数增长有关，但变成两倍、成倍增殖和可能产生歧义的两倍表达不同。",
        "double 明确表示变为原来的两倍；multiply 表示数量成倍增加但倍数需另给；increase twofold 常被理解为变为两倍，却可能与“增加两倍”混淆，图表中优先写 double。",
        "两倍最清楚写 double；多倍增长写 multiply 并给倍数；increase twofold 谨慎使用。",
        (("终值", "double = final value is 2× original；increase by 100% 也等于 double。"),
         ("信息量", "multiply 本身不说明具体倍数；twofold 指两倍关系。"),
         ("清晰度", "避免中文“增加两倍”式歧义；直接给起点、终点或写 double。")),
        {
            "double": item("verb/adjective", "翻一番；两倍的", "become or make twice as large", "明确表示终值是起始值的两倍。", ["double from A to B", "double in size"], "中性、正式，图表表达清晰。", "double 不表示在原值上再增加两倍；那将是 triple。", "The number of users doubled from 25,000 to 50,000.", "用户数量从 2.5 万翻了一番，达到 5 万。"),
            "multiply": item("verb", "成倍增加；乘", "increase greatly in number or perform multiplication", "表示数量快速增多，具体倍数需由补语或数字说明。", ["multiply fivefold", "multiply by three"], "中性；数学和增长语境。", "只写 multiplied 不能让读者知道最终是几倍。", "The number of outlets multiplied fivefold within a decade.", "门店数量在十年内增长到原来的五倍。"),
            "increase twofold": item("verb phrase", "增至两倍；两倍增长", "increase to about twice the original level", "常用于表示变为约两倍，但自然度和解析可能因语境而异。", ["increase twofold over the period", "a twofold increase"], "正式科技文本可见；考试写作应以清晰为先。", "不要把 a twofold increase 与 increase by two times 混写；能写 doubled 时优先写 doubled。", "Capacity increased twofold, from 300 to 600 units.", "产能从 300 件增至 600 件，变为原来的两倍。"),
        },
    ),
    comparison(
        "ielts-average-mean-median", ("average", "mean", "median"),
        "中文都可能译成平均或中间水平，但日常平均、算术平均数和中位数不是同一统计量。",
        "average 是通用词，在未说明时常指算术平均；mean 是把数值相加后除以个数；median 是排序后位于中间的值，对极端值不那么敏感。",
        "通用描述是 average，算术定义是 mean，排序中点是 median。",
        (("计算", "mean = sum/n；median = ordered middle value；average 需由资料说明采用哪种平均。"),
         ("极端值", "mean 易受极端值影响；median 对偏斜收入等数据通常更稳健。"),
         ("报告", "不能为了同义替换把 mean 改成 median；先确认图表指标名称。")),
        {
            "average": item("noun/adjective", "平均数；平均的", "a typical or central value, often the arithmetic mean", "日常或概括性地表示一组数据的平均水平。", ["on average", "the average income"], "中性、通用。", "average 不总是严格指 mean；正式统计报告应沿用图表定义。", "On average, commuters spent 38 minutes travelling to work.", "通勤者上班路上平均花费 38 分钟。"),
            "mean": item("noun/adjective", "算术平均数；平均的", "the sum of values divided by the number of values", "明确指算术平均数这一统计量。", ["the arithmetic mean", "a mean score of"], "正式、统计和研究语境。", "偏斜数据中 mean 不等于典型个体，也不能替代 median。", "The mean test score rose from 68 to 74.", "测试成绩的算术平均分从 68 分升至 74 分。"),
            "median": item("noun/adjective", "中位数；中位的", "the middle value after observations are ordered", "把数据排序后取中间位置，突出分布中点。", ["the median income", "a median age of"], "正式、统计语境。", "median 不是把最高和最低简单相加除以二，也不是 mean 的同义词。", "Median household income was lower than the arithmetic mean.", "家庭收入中位数低于算术平均数。"),
        },
    ),
    comparison(
        "ielts-total-sum-aggregate", ("total", "sum", "aggregate"),
        "都可表示合计，但最终总量、加法结果和合并整体的语域不同。",
        "total 是把所有相关项计入后的总数；sum 强调数字相加所得结果；aggregate 是多个单位合并形成的整体，语域更正式。",
        "最终总量用 total，加法结果用 sum，多个单位合并用 aggregate。",
        (("焦点", "total 关注完整结果；sum 关注加法关系；aggregate 关注由多个部分汇集。"),
         ("词性", "total 和 aggregate 可作名词、形容词或动词；sum 常作名词，sum up 另有总结义。"),
         ("搭配", "the total number；the sum of A and B；aggregate demand/data。")),
        {
            "total": item("noun/adjective/verb", "总数；总计的；合计", "the complete amount after all relevant parts are included", "最通用地表示所有相关项目合并后的最终量。", ["the total number of", "a total of 500"], "中性、正式，图表高频。", "the total number 接可数名词；the total amount 接不可数名词。", "A total of 1,240 applications were received.", "共收到 1,240 份申请。"),
            "sum": item("noun/verb", "总和；合计", "the result of adding particular numbers or amounts", "突出若干数值经过加法得到结果。", ["the sum of A and B", "sum to 100"], "中性；数学和财务语境常见。", "描述人口总量时 total 通常比 the sum 更自然，除非强调计算。", "The sum of the three categories was 96 million dollars.", "三个类别的合计为 9,600 万美元。"),
            "aggregate": item("noun/adjective/verb", "总量；合计的；汇总", "a whole formed by combining several separate units", "强调多个个体或分类汇集成整体。", ["aggregate demand", "in aggregate"], "正式，经济、统计和数据处理语境。", "普通图表总数不必为显得正式而用 aggregate。", "In aggregate, the four regions generated 70% of national output.", "总体合计来看，这四个地区贡献了全国 70% 的产出。"),
        },
    ),
    comparison(
        "ielts-difference-gap-disparity", ("difference", "gap", "disparity"),
        "都可译为差异，但中性不同、可度量间距和带不平等意味的悬殊不同。",
        "difference 是最中性的不同或数值差；gap 把差异看作两个水平间的距离；disparity 强调显著且常被认为不公平的差距。",
        "中性不同用 difference，水平间距用 gap，悬殊不平等用 disparity。",
        (("评价", "difference 中性；gap 可中性也可暗示待弥合；disparity 常带社会不平等评价。"),
         ("可量化", "a difference of 10 points；a gap between groups；regional disparities。"),
         ("范围", "微小数据差异通常不用 disparity；类别性质不同未必能计算 gap。")),
        {
            "difference": item("noun", "差异；差值", "a way in which things are not the same, or the numerical result of subtraction", "中性表示性质不同或两个数值之差。", ["a difference of 10 points", "the difference between A and B"], "中性、通用。", "difference by 10 不自然；数值差通常写 a difference of 10。", "There was a difference of nine percentage points between the groups.", "两组之间相差 9 个百分点。"),
            "gap": item("noun", "差距；间隔", "a measurable separation between levels, groups, or outcomes", "把两个水平或群体之间的差异概念化为距离。", ["the gap between A and B", "narrow the gap"], "中性偏正式；教育、收入和性别数据常见。", "gap 不适合所有类别差异；还要避免把相关性直接写成待弥合的问题。", "The employment gap between the two age groups narrowed after 2020.", "2020 年后，两个年龄组之间的就业差距缩小了。"),
            "disparity": item("noun", "悬殊；不平等差距", "a marked and often unfair difference between groups", "强调差距明显，常涉及资源、机会或结果不平等。", ["regional disparities", "a disparity in income"], "正式，社会政策和学术语境。", "普通的 1% 差别不应夸大为 disparity，除非背景证明其重要。", "The data reveal a substantial disparity in access to healthcare.", "数据显示医疗服务可及性存在显著差距。"),
        },
    ),
)
