from __future__ import annotations

try:
    from .lexical_compare_data import comparison, item
except ImportError:
    from lexical_compare_data import comparison, item


EXTENDED_CURATED_COMPARISONS = (
    comparison(
        "compose-comprise-constitute-consist-of",
        ("compose", "comprise", "constitute", "consist of"),
        "中文都可能译成“组成、构成”，但整体与部分的主语方向不同。",
        "部分 compose/constitute 整体；整体 comprises/consists of 部分。compose 也常用被动 be composed of。",
        "部分 compose/constitute 整体；整体 comprises/consists of 部分。",
        (
            ("方向", "Parts compose/constitute the whole；the whole comprises/consists of parts。"),
            ("语态", "be composed of 很常见；consist of 不用被动；comprise 通常直接用主动。"),
            ("语义", "constitute 还可表示“算作、构成某种状态”；compose 还可表示创作或使镇定。"),
        ),
        {
            "compose": item("verb", "组成；构成；创作", "form a whole by combining parts, or create a work", "作“组成”时，主语通常是部分；被动结构由整体作主语。", ["parts compose the whole", "be composed of", "compose music"], "正式和学术语境常见。", "主动句不要写 The book composes ten chapters；应说 comprises 或 consists of。", "Five short sections compose the final report.", "五个短小部分组成了最终报告。"),
            "comprise": item("verb", "包括；由……组成", "contain or consist of specified parts", "主语通常是整体，宾语列出组成部分。", ["comprise three sections", "be comprised of", "together comprise"], "正式和学术写作高频。", "传统规范偏好 The whole comprises the parts；be comprised of 已广泛使用但正式写作可优先用 be composed of。", "The course comprises six taught modules.", "这门课程包括六个授课模块。"),
            "constitute": item("verb", "构成；组成；算作", "form a whole or amount to a particular state", "主语常是部分，也可表示某行为达到某种性质或法律状态。", ["constitute a majority", "constitute evidence", "be constituted by"], "正式、法律和学术语域常见。", "列出整体所含部分时，不要机械替换 comprise。", "International students constitute a third of the cohort.", "国际学生构成该年级学生的三分之一。"),
            "consist of": item("verb phrase", "由……组成", "be made up of particular parts", "主语是整体，of 后列出部分，强调构成事实。", ["consist of three parts", "consist mainly of", "consist entirely of"], "中性和正式语境都常见。", "不用被动 be consisted of，也通常不用进行时。", "The dataset consists of interviews and survey responses.", "该数据集由访谈和问卷回答组成。"),
        },
    ),
    comparison(
        "include-contain-involve",
        ("include", "contain", "involve"),
        "中文都可能译成“包括、包含”，但边界、容纳关系和参与过程不同。",
        "include 列举整体中的部分；contain 强调内部装有或含有；involve 强调活动必然需要或牵涉。",
        "列举部分 include，内部含有 contain，过程牵涉 involve。",
        (("关系", "include 是成员关系；contain 是容器或内容关系；involve 是过程与必要条件关系。"), ("完整性", "include 的列举不一定穷尽；contain 常描述实际内容；involve 强调不可避免地需要。"), ("句型", "include doing；contain a substance；involve doing/someone。")),
        {
            "include": item("verb", "包括；把……列入", "have something as one part of a larger whole", "列出整体中的一个或多个成员，不一定是全部。", ["include something", "include doing", "including but not limited to"], "中性高频。", "物理容器中含某物时常用 contain。", "The fee includes access to the online archive.", "费用包括在线档案库的访问权限。"),
            "contain": item("verb", "包含；容纳；含有", "hold something within limits or inside a container", "强调某物位于内部，也可表示控制、抑制。", ["contain information", "contain traces of", "contain the spread"], "中性、科学和技术语境高频。", "谈活动所需步骤时通常用 involve，不用 contain。", "The sample contained small amounts of lead.", "样本中含有少量铅。"),
            "involve": item("verb", "涉及；需要；使参与", "require something as a necessary part or affect participants", "强调一项活动必然牵涉某步骤、风险或人员。", ["involve doing", "involve someone in", "be involved in"], "正式和日常语境都常见。", "单纯列举套餐内容时通常用 include。", "The role involves working with confidential data.", "该职位需要处理机密数据。"),
        },
    ),
    comparison(
        "achieve-accomplish-attain",
        ("achieve", "accomplish", "attain"),
        "中文都可能译成“实现、达到”，但搭配对象和正式程度不同。",
        "achieve 达成目标或结果；accomplish 完成任务；attain 经过努力达到水平、状态或地位。",
        "目标结果 achieve，具体任务 accomplish，水平境界 attain。",
        (("宾语", "achieve a goal/result；accomplish a task/mission；attain a level/status。"), ("过程", "三者都可含努力，但 accomplish 更突出任务完成，attain 更突出到达某点。"), ("语域", "attain 最正式；achieve 最通用；accomplish 常用于可完成事项。")),
        {
            "achieve": item("verb", "实现；取得；达到", "successfully reach a goal or produce a desired result", "强调获得预期成果。", ["achieve a goal", "achieve success", "achieve a reduction"], "中性和正式语境高频。", "不要说 achieve a task；通常用 accomplish/complete a task。", "The intervention achieved a significant reduction in errors.", "该干预显著减少了错误。"),
            "accomplish": item("verb", "完成；实现", "complete a task or successfully carry out an objective", "强调把具体任务或使命做完。", ["accomplish a task", "accomplish the mission", "accomplish little"], "略正式。", "谈达到某一语言水平时通常用 attain/reach。", "The team accomplished the work ahead of schedule.", "团队提前完成了工作。"),
            "attain": item("verb", "达到；获得", "reach a level, state, age, or position after effort", "强调到达某一标准、状态或地位。", ["attain a level", "attain independence", "attain the age of"], "正式、学术和法律语境常见。", "日常完成小任务时显得过于正式。", "Few participants attained the highest proficiency level.", "很少有参与者达到最高熟练度。"),
        },
    ),
    comparison(
        "acquire-obtain-gain",
        ("acquire", "obtain", "gain"),
        "中文都可能译成“获得”，区别在逐渐拥有、取得具体对象和增加收益。",
        "acquire 强调获得并拥有知识、技能或资产；obtain 强调通过行动取得；gain 强调增加有价值的东西。",
        "逐渐拥有 acquire，设法取得 obtain，增加收益 gain。",
        (("对象", "acquire skills/assets；obtain permission/data；gain experience/weight/support。"), ("过程", "acquire 可渐进；obtain 常有申请或程序；gain 常体现增长或收益。"), ("语域", "obtain/acquire 较正式；gain 日常和正式都常见。")),
        {
            "acquire": item("verb", "获得；习得；收购", "come to possess knowledge, skill, or property", "强调从无到有并形成较稳定拥有。", ["acquire a skill", "acquire knowledge", "acquire a company"], "正式和学术语境高频。", "一次性拿到许可通常更自然地用 obtain。", "Children acquire vocabulary through repeated exposure.", "儿童通过反复接触习得词汇。"),
            "obtain": item("verb", "获得；取得", "get something through effort, request, or procedure", "强调成功拿到具体所需对象。", ["obtain permission", "obtain data", "obtain a copy"], "较正式，研究和行政语境常见。", "表示体重或信心增加通常用 gain。", "Researchers obtained consent from every participant.", "研究人员获得了每位参与者的同意。"),
            "gain": item("verb/noun", "获得；增加；收益", "get or increase something useful or desirable", "强调经验、优势、支持或数值的增长。", ["gain experience", "gain access to", "gain weight"], "中性高频。", "经正式程序拿证书时不一定能直接替换 obtain。", "The placement helped her gain practical experience.", "这次实习帮助她获得了实践经验。"),
        },
    ),
    comparison(
        "assure-ensure-insure",
        ("assure", "ensure", "insure"),
        "中文都可能与“保证”有关，但对象分别是人、结果和保险风险。",
        "assure 使某人放心；ensure 确保结果发生；insure 为人或财产投保。",
        "让人放心 assure，确保结果 ensure，买保险 insure。",
        (("宾语", "assure someone；ensure something/that；insure property/person against risk。"), ("语义", "assure 是沟通与信心；ensure 是结果控制；insure 是金融保障。"), ("地区差异", "美式英语偶尔用 insure 表示 ensure，但正式写作最好区分。")),
        {
            "assure": item("verb", "向……保证；使放心", "tell someone confidently so that they stop worrying", "直接作用于人及其信心。", ["assure someone that", "assure someone of", "rest assured"], "中性偏正式。", "不能说 assure the accuracy；应说 ensure the accuracy。", "The supervisor assured us that the data were secure.", "导师向我们保证数据是安全的。"),
            "ensure": item("verb", "确保；保证", "make certain that something happens or is true", "通过措施保证结果或条件。", ["ensure that", "ensure access", "ensure compliance"], "正式和学术写作高频。", "后面直接接人表示安慰时通常用 assure。", "Double-checking the labels ensures accurate coding.", "复核标签可以确保编码准确。"),
            "insure": item("verb", "给……投保；承保", "protect financially against loss through insurance", "专指保险合同和风险补偿。", ["insure a car", "insure against loss", "fully insured"], "保险和法律语境。", "一般的“确保研究质量”不用 insure。", "The university insures its equipment against theft.", "大学为设备投保以防盗窃损失。"),
        },
    ),
    comparison(
        "imply-infer",
        ("imply", "infer"),
        "中文都涉及“暗示、推断”，但信息发送者和接收者方向相反。",
        "说话者或证据 imply；听者或研究者 infer。",
        "发出暗示 imply，从暗示得出结论 infer。",
        (("角色", "writer/speaker/data imply；reader/listener/researcher infers。"), ("证据方向", "imply 把未明说的信息编码进去；infer 从线索解码出结论。"), ("句型", "imply that；infer something from evidence。")),
        {
            "imply": item("verb", "暗示；意味着", "communicate or indicate something without stating it directly", "主语是话语、行为或证据来源。", ["imply that", "seem to imply", "strongly imply"], "中性和学术语境高频。", "读者从文本得出结论时用 infer。", "The wording implies that participation is optional.", "这一措辞暗示参与是自愿的。"),
            "infer": item("verb", "推断；推知", "reach a conclusion from evidence or reasoning", "主语是解释线索并形成结论的人。", ["infer from", "infer that", "it can be inferred"], "正式和学术语境高频。", "作者让人意会某事时通常用 imply。", "We can infer from the results that the effect was temporary.", "我们可以从结果推断该影响是暂时的。"),
        },
    ),
    comparison(
        "adapt-adopt",
        ("adapt", "adopt"),
        "中文都可能被误记成“采用、适应”，但一个是调整适配，一个是选择采用。",
        "adapt 改变以适应条件；adopt 决定接受方法、政策或身份关系。",
        "改到适合用 adapt，选择采用用 adopt。",
        (("动作", "adapt 涉及修改；adopt 涉及选择和接受。"), ("结构", "adapt to / adapt something for；adopt a policy/method/child。"), ("结果", "可以先 adopt 一个方法，再 adapt it to local needs。")),
        {
            "adapt": item("verb", "适应；改编；调整", "change to suit new conditions or a particular use", "强调自身变化或对材料进行修改。", ["adapt to change", "adapt something for", "be adapted from"], "中性和正式语境都常见。", "只是决定使用某方法时用 adopt。", "The questionnaire was adapted for younger participants.", "该问卷经过调整以适用于更年轻的参与者。"),
            "adopt": item("verb", "采用；采纳；收养", "choose to accept and begin using an approach or policy", "强调作出选择并开始使用，也可表示收养。", ["adopt a method", "adopt a policy", "adopt a child"], "正式写作高频。", "表示逐渐适应环境时不用 adopt to。", "The team adopted a more transparent review process.", "团队采用了更透明的审查流程。"),
        },
    ),
    comparison(
        "rise-raise-arise",
        ("rise", "raise", "arise"),
        "中文都可能与“上升、产生”有关，但及物性和语义不同。",
        "rise 自己上升；raise 把某物提高；arise 表示问题或情况出现。",
        "自己升 rise，举起提高 raise，问题出现 arise。",
        (("及物性", "rise/arise 不及物；raise 及物，必须有宾语。"), ("过去式", "rise-rose-risen；raise-raised-raised；arise-arose-arisen。"), ("搭配", "prices rise；raise prices/questions；problems arise。")),
        {
            "rise": item("verb/noun", "上升；升起；增长", "move upward or increase without a direct object", "主语自身发生向上移动或数值增长。", ["prices rise", "rise sharply", "rise from ... to ..."], "中性和数据写作高频。", "不能说 rise the price；应说 raise the price。", "Average temperatures rose by two degrees.", "平均气温上升了两度。"),
            "raise": item("verb", "举起；提高；提出；筹集", "cause something to move upward or increase", "主语对宾语施加作用。", ["raise prices", "raise a question", "raise funds"], "中性高频，搭配很多。", "没有宾语的数值上升用 rise。", "The report raises several ethical concerns.", "报告提出了若干伦理问题。"),
            "arise": item("verb", "出现；产生；起因于", "come into existence, especially as a problem or situation", "强调情况、需要或问题发生。", ["problems arise", "arise from", "should the need arise"], "较正式。", "一般数值增长不用 arise。", "Difficulties arose during data collection.", "数据收集期间出现了困难。"),
        },
    ),
    comparison(
        "lie-lay",
        ("lie", "lay"),
        "中文都可能与“躺、放”有关，但 lie 不及物，lay 必须有宾语。",
        "人或物自己躺着用 lie；把某物放下用 lay。",
        "自己躺 lie，放下东西 lay。",
        (("及物性", "lie 不接宾语；lay 接被放置的对象。"), ("词形", "lie-lay-lain；lay-laid-laid。另一个 lie-lied-lied 表示说谎。"), ("句型", "lie on the table；lay the book on the table。")),
        {
            "lie": item("verb", "躺；位于；说谎", "be in a horizontal position or be located", "作躺/位于时不及物；说谎是另一个词形系统。", ["lie down", "lie on", "lie ahead"], "中性高频。", "不能说 lie the book on the desk。", "The original documents lie in the archive.", "原始文件存放在档案馆里。"),
            "lay": item("verb", "放置；铺设；产卵", "put something down in a particular position", "主语把宾语放到某处。", ["lay something on", "lay the foundation", "lay eggs"], "中性高频。", "表示人躺下时用 lie down，不用 lay down，除非后接宾语。", "She laid the maps on the table.", "她把地图放在桌上。"),
        },
    ),
    comparison(
        "accept-receive",
        ("accept", "receive"),
        "中文都可能译成“接受、收到”，但 receive 是到达事实，accept 是主观同意接纳。",
        "东西到手是 receive，愿意接纳是 accept。",
        "收到 receive，同意收下 accept。",
        (("意愿", "receive 不保证愿意；accept 表示同意或认可。"), ("对象", "receive a message/package；accept an offer/apology。"), ("顺序", "可以 receive an invitation but decline to accept it。")),
        {
            "accept": item("verb", "接受；认可；同意", "agree to take, believe, or approve something", "强调意愿、认可或同意。", ["accept an offer", "accept responsibility", "widely accepted"], "中性高频。", "只描述邮件到达时用 receive。", "She accepted the offer after reviewing the terms.", "她审阅条款后接受了这份提议。"),
            "receive": item("verb", "收到；接到；受到", "be given or experience something that arrives", "强调信息、物品或待遇到达接收者。", ["receive an email", "receive treatment", "receive funding"], "中性偏正式；日常口语也常用 get。", "receive 不表示赞同或愿意接受。", "We received more than two hundred responses.", "我们收到了两百多份回复。"),
        },
    ),
    comparison(
        "refuse-reject-decline",
        ("refuse", "reject", "decline"),
        "中文都可能译成“拒绝”，但对象、语气和句法不同。",
        "refuse 表示不愿做或不给；reject 否决想法、申请或物品；decline 是较礼貌地谢绝。",
        "不肯做 refuse，判定不要 reject，礼貌谢绝 decline。",
        (("句型", "refuse to do；reject a proposal/application；decline an invitation/to comment。"), ("语气", "refuse 较直接；reject 可制度化；decline 较礼貌正式。"), ("其他义项", "decline 还可表示下降；reject 还可表示不合格品。")),
        {
            "refuse": item("verb", "拒绝；不肯", "say or show that you will not do or give something", "强调主语意志上不愿行动。", ["refuse to do", "refuse permission", "refuse someone entry"], "较直接。", "不能说 refuse the proposal 在所有语境替代 reject；正式否决更常用 reject。", "Two participants refused to answer the question.", "两名参与者拒绝回答这个问题。"),
            "reject": item("verb/noun", "拒绝；否决；驳回", "decide that an idea, request, or object is unacceptable", "强调评估后判定不接受或不合格。", ["reject an application", "reject a hypothesis", "outright rejection"], "正式、学术和行政语境高频。", "礼貌谢绝邀请时 decline 更自然。", "The journal rejected the manuscript after review.", "期刊在评审后拒绝了这篇稿件。"),
            "decline": item("verb/noun", "谢绝；下降；衰退", "politely refuse an offer or become smaller", "作拒绝时语气较礼貌，也有下降义。", ["decline an invitation", "decline to comment", "a sharp decline"], "礼貌正式。", "强硬不配合时 refuse 更准确。", "She declined the invitation because of a prior commitment.", "她因已有安排而谢绝了邀请。"),
        },
    ),
    comparison(
        "common-ordinary-normal-usual",
        ("common", "ordinary", "normal", "usual"),
        "中文都可能译成“普通、常见、正常”，判断标准不同。",
        "common 看出现频率；ordinary 看不特别；normal 看符合标准状态；usual 看某人或情境一贯如此。",
        "常见 common，不特别 ordinary，符合正常状态 normal，一贯如此 usual。",
        (("参照标准", "common=群体频率；ordinary=特殊性；normal=规范范围；usual=惯例。"), ("典型搭配", "common error；ordinary people；normal range；usual routine。"), ("语气", "ordinary 有时暗含平淡；normal 可能涉及规范判断，需谨慎。")),
        {
            "common": item("adjective/noun", "常见的；共同的", "frequent, widespread, or shared by several people", "强调出现频率高或共同拥有。", ["a common mistake", "common among", "have in common"], "中性高频。", "符合医学参考区间通常用 normal range。", "This is a common error among new researchers.", "这是新研究人员常犯的错误。"),
            "ordinary": item("adjective", "普通的；平常的", "not special, unusual, or distinctive", "强调没有特殊地位或特征。", ["ordinary people", "an ordinary day", "out of the ordinary"], "中性，有时略显平淡。", "出现频率高不一定意味着 ordinary。", "The device looks ordinary but contains advanced sensors.", "这台设备外表普通，却装有先进传感器。"),
            "normal": item("adjective/noun", "正常的；标准的", "within an expected or healthy range", "强调符合预期、规则或功能状态。", ["normal conditions", "return to normal", "within the normal range"], "科学、医学和日常语境常见。", "谈个人习惯时 usual 往往更准确。", "The readings returned to normal after calibration.", "校准后读数恢复正常。"),
            "usual": item("adjective", "通常的；惯常的", "happening or used in the way that is typical for a person or situation", "强调与过去惯例或个人习惯一致。", ["as usual", "the usual procedure", "usual practice"], "中性高频。", "群体中普遍存在的现象常用 common。", "We followed the usual procedure for anonymising data.", "我们按照惯常程序对数据进行了匿名化。"),
        },
    ),
    comparison(
        "possible-probable-likely",
        ("possible", "probable", "likely"),
        "中文都可能译成“可能”，但 possible 只表示可发生，probable/likely 表示较大概率。",
        "possible 是不排除；probable 是证据显示大概会发生；likely 是常用的高概率判断。",
        "能发生 possible，大概会发生 probable/likely。",
        (("概率", "possible 的门槛最低；probable 和 likely 通常表示超过一半或相对较高。"), ("句法", "it is possible/probable that；someone is likely to do。"), ("语域", "probable 稍正式；likely 最灵活。")),
        {
            "possible": item("adjective", "可能的；可行的", "able to happen or be done, without claiming high probability", "只排除不可能，不说明发生概率高。", ["it is possible that", "as soon as possible", "a possible explanation"], "中性高频。", "有充分证据表明大概会发生时 likely/probable 更准确。", "It is possible that other factors affected the result.", "其他因素可能影响了结果。"),
            "probable": item("adjective", "很可能的；大概的", "supported by evidence as more likely than not", "正式判断某结果有较大概率。", ["it is probable that", "the probable cause", "highly probable"], "稍正式，分析和法律语境常见。", "人作主语时通常不用 someone is probable to。", "The most probable cause was a recording error.", "最可能的原因是记录错误。"),
            "likely": item("adjective/adverb", "可能的；很可能", "expected to happen based on current evidence", "灵活表达较高可能性，可用人或事物作主语。", ["be likely to do", "it is likely that", "most likely"], "中性高频。", "仅表示理论上可行时不要夸大为 likely。", "Participants are likely to remember emotionally vivid examples.", "参与者很可能记住情感鲜明的例子。"),
        },
    ),
    comparison(
        "problem-issue-question",
        ("problem", "issue", "question"),
        "中文都可能译成“问题”，但分别强调困难、议题和待回答内容。",
        "problem 需要解决；issue 需要讨论或处理；question 需要回答或研究。",
        "要解决 problem，要讨论 issue，要回答 question。",
        (("核心动作", "solve a problem；address/discuss an issue；answer/investigate a question。"), ("语气", "issue 有时比 problem 委婉；question 可完全没有负面含义。"), ("学术用法", "research question 是研究问题；methodological problem 是方法困难。")),
        {
            "problem": item("noun", "问题；困难；难题", "a difficulty or harmful situation needing a solution", "强调障碍、错误或不理想状态。", ["solve a problem", "a serious problem", "problem with"], "中性高频。", "中性讨论主题不一定是 problem。", "Missing data created a serious problem for the analysis.", "数据缺失给分析造成了严重问题。"),
            "issue": item("noun/verb", "议题；问题；事项", "an important topic or matter that requires attention", "强调需要讨论、决定或处理的事项。", ["address an issue", "raise an issue", "a controversial issue"], "正式和职场语境高频。", "有唯一答案的考试题通常用 question。", "The report addresses the issue of unequal access.", "报告讨论了获取机会不平等的问题。"),
            "question": item("noun/verb", "问题；疑问；质疑", "something asked, investigated, or left uncertain", "强调信息缺口、待回答内容或研究对象。", ["answer a question", "research question", "call into question"], "中性和学术语境高频。", "设备故障这类困难通常是 problem。", "The study asks an important question about trust.", "该研究提出了一个关于信任的重要问题。"),
        },
    ),
    comparison(
        "method-approach-way",
        ("method", "approach", "way"),
        "中文都可能译成“方法”，但正式程度和抽象层级不同。",
        "method 是具体、系统的程序；approach 是整体思路或策略；way 是最宽泛的做法。",
        "具体步骤 method，整体思路 approach，泛指做法 way。",
        (("层级", "approach 可包含多个 methods；way 可指任何实现形式。"), ("句法", "method of/for doing；approach to doing；way of/to do。"), ("语域", "method/approach 学术高频；way 日常更自然。")),
        {
            "method": item("noun", "方法；方法论中的具体程序", "a systematic procedure for doing or investigating something", "强调可重复的步骤、技术或程序。", ["research method", "method of doing", "a reliable method"], "正式和学术语境高频。", "宏观理论立场通常更适合用 approach。", "The team used a mixed-method research design.", "团队采用了混合方法研究设计。"),
            "approach": item("noun/verb", "方法；思路；处理方式", "a general strategy or perspective used to deal with something", "强调面对问题的总体方向、框架或策略。", ["an approach to doing", "adopt an approach", "a theoretical approach"], "正式和学术语境高频。", "固定实验步骤通常称 method，不只是 approach。", "The course takes a practical approach to statistics.", "这门课程采用实践导向的统计学教学方法。"),
            "way": item("noun", "方式；办法；道路", "a general manner or means of doing something", "范围最广，可以指习惯、形式、途径或方法。", ["a way to do", "a way of doing", "in this way"], "日常高频，正式写作也可使用。", "方法章节中的技术程序通常优先用 method。", "There are several ways to visualise the findings.", "有多种方式可以把研究结果可视化。"),
        },
    ),
    comparison(
        "purpose-goal-objective-aim",
        ("purpose", "goal", "objective", "aim"),
        "中文都可能译成“目的、目标”，但功能、时间尺度和可测量性不同。",
        "purpose 解释为什么做；goal 描写期望终点；objective 是具体可测目标；aim 是计划努力实现的方向。",
        "为什么做 purpose，想去哪里 goal，具体指标 objective，努力方向 aim。",
        (("抽象程度", "purpose 最根本；goal/aim 指方向；objective 通常最具体可测。"), ("学术写作", "the purpose of the study；the study aims to；research objectives。"), ("可数性", "goal/objective/aim 可数；purpose 可数但常用单数说明功能。")),
        {
            "purpose": item("noun", "目的；用途；意义", "the reason why something exists or is done", "回答“为什么做”或“用来做什么”。", ["the purpose of", "serve a purpose", "for the purpose of"], "中性和正式语境高频。", "具体量化指标通常用 objective。", "The purpose of the pilot was to test feasibility.", "试点的目的是测试可行性。"),
            "goal": item("noun", "目标；终点", "a desired long-term result toward which effort is directed", "强调希望最终达到的状态。", ["achieve a goal", "long-term goal", "set a goal"], "中性高频。", "研究中的具体操作步骤不都称 goal。", "Our long-term goal is to reduce preventable errors.", "我们的长期目标是减少可预防的错误。"),
            "objective": item("noun/adjective", "具体目标；客观的", "a specific and often measurable result to be achieved", "作名词时强调明确、可检验的目标。", ["research objective", "meet an objective", "a measurable objective"], "正式、项目管理和研究语境高频。", "宽泛愿景通常用 goal/aim。", "The first objective is to compare the two groups.", "第一个具体目标是比较这两组。"),
            "aim": item("noun/verb", "目标；旨在", "an intended result or direction of effort", "可作名词或动词，常用于研究目的陈述。", ["aim to do", "aim at doing", "the main aim"], "英式和学术英语高频。", "aim at doing 与 aim to do 结构不要混淆。", "The study aims to identify barriers to access.", "该研究旨在识别获取服务的障碍。"),
        },
    ),
    comparison(
        "result-consequence-outcome",
        ("result", "consequence", "outcome"),
        "中文都可能译成“结果、后果”，但中性程度和使用领域不同。",
        "result 是最通用的因果产物；consequence 常强调后续影响，尤其负面；outcome 强调过程结束后的最终状态。",
        "通用结果 result，后续影响 consequence，最终结局 outcome。",
        (("语气", "result/outcome 通常中性；consequence 常带严重或负面色彩。"), ("领域", "research results；consequences of policy；health/learning outcomes。"), ("因果", "as a result；as a consequence；the outcome of a process。")),
        {
            "result": item("noun/verb", "结果；导致", "what happens or is found because of an action or process", "范围最广，可指实验发现、比赛比分或因果产物。", ["research results", "as a result", "result in/from"], "中性高频。", "强调长期严重后果时 consequence 更有力。", "The results support the original hypothesis.", "结果支持最初的假设。"),
            "consequence": item("noun", "后果；影响", "an effect that follows an action, often serious or unwanted", "强调行为带来的后续影响和责任。", ["a consequence of", "serious consequences", "as a consequence"], "正式语境常见。", "中性实验数值通常称 results，不称 consequences。", "The delay had serious consequences for patients.", "这次延误给患者带来了严重后果。"),
            "outcome": item("noun", "结果；结局；成效", "the final state produced by a process, intervention, or event", "强调过程或干预结束后的最终状态。", ["health outcomes", "learning outcome", "possible outcome"], "医学、教育、政策和项目评估高频。", "分析表格中的每项发现不一定都是 outcome。", "The programme improved employment outcomes.", "该项目改善了就业成效。"),
        },
    ),
    comparison(
        "join-attend-participate",
        ("join", "attend", "participate"),
        "中文都可能译成“参加”，但分别强调加入群体、到场和积极参与。",
        "join 加入人或组织；attend 出席活动；participate 实际参与活动过程。",
        "加入 join，到场 attend，投入参与 participate。",
        (("宾语", "join a group/someone；attend a meeting/class；participate in an activity。"), ("参与程度", "attend 只保证到场；participate 强调实际投入。"), ("介词", "join 后通常不加 in；participate 必须常与 in 连用。")),
        {
            "join": item("verb", "加入；参加；与……会合", "become a member or come together with people", "强调成为团体成员或与某人会合。", ["join a team", "join someone", "join in"], "中性高频。", "出席一场会议通常用 attend，不说 join a meeting（线上语境偶有使用）。", "She joined the research team in September.", "她九月加入了研究团队。"),
            "attend": item("verb", "出席；参加；上课", "be present at an event, meeting, or institution", "核心是到场，不保证积极发言。", ["attend a meeting", "attend class", "well attended"], "中性偏正式。", "不能说 attend in the discussion；积极参与用 participate in。", "More than five hundred delegates attended the conference.", "五百多名代表出席了会议。"),
            "participate": item("verb", "参与；参加", "take an active part in an activity or process", "强调实际投入活动，而不只是出现。", ["participate in", "actively participate", "research participants"], "正式和学术语境高频。", "participate 后通常需要 in，再接活动。", "Students participated in a group discussion.", "学生们参与了小组讨论。"),
        },
    ),
    comparison(
        "provide-supply-offer",
        ("provide", "supply", "offer"),
        "中文都可能译成“提供”，但满足需要、持续供给和主动提议的侧重点不同。",
        "provide 提供所需资源；supply 持续或批量供应；offer 主动提出可供选择的东西。",
        "满足需要 provide，持续供给 supply，主动拿出来 offer。",
        (("结构", "provide someone with something；supply something to someone；offer someone something。"), ("关系", "supply 常有供应链或数量；offer 强调接受与否由对方决定。"), ("对象", "provide information/support；supply goods/power；offer help/choice/job。")),
        {
            "provide": item("verb", "提供；供给", "make something needed available", "强调满足需求或使资源可获得。", ["provide something", "provide someone with", "provide for"], "中性和正式语境高频。", "不能说 provide someone something 在严格正式写作中；优先 provide someone with something。", "The portal provides students with access to journals.", "该门户为学生提供期刊访问权限。"),
            "supply": item("verb/noun", "供应；供给；供应量", "deliver an amount of goods, energy, or resources", "强调有数量、持续性或供应体系。", ["supply something to", "supply someone with", "water supply"], "商业、工程和公共服务语境高频。", "主动提出帮助通常用 offer。", "The grid supplies electricity to remote villages.", "电网为偏远村庄供电。"),
            "offer": item("verb/noun", "提供；提出；报价", "present something for someone to accept or reject", "强调主动提出一个机会、帮助或选项。", ["offer someone something", "offer to do", "make an offer"], "中性高频。", "持续供应大量原料通常用 supply。", "The university offers free language support.", "大学提供免费的语言支持。"),
        },
    ),
    comparison(
        "require-need-demand",
        ("require", "need", "demand"),
        "中文都可能译成“需要、要求”，但必要性来源和强制程度不同。",
        "need 是一般必要；require 是规则或条件所需；demand 是强烈要求或高强度需求。",
        "一般需要 need，条件规定 require，强烈索取 demand。",
        (("来源", "need 来自实际需要；require 来自规则/条件；demand 来自人或市场的强烈压力。"), ("语气", "demand 最强；require 正式客观；need 最通用。"), ("句型", "need to do；require someone to do / require doing；demand that/to know。")),
        {
            "require": item("verb", "要求；需要；规定", "make something necessary because of a rule or condition", "强调客观条件、制度或任务规定。", ["require someone to do", "require approval", "require doing"], "正式和技术语境高频。", "个人日常需要通常用 need 更自然。", "The protocol requires participants to sign a consent form.", "该方案要求参与者签署同意书。"),
            "need": item("verb/noun", "需要；必要", "lack something necessary or consider it necessary", "最通用地表达实际必要性。", ["need to do", "need something", "in need of"], "中性高频。", "强硬命令或市场需求量不一定用 need。", "We need more evidence before changing the policy.", "在改变政策之前，我们需要更多证据。"),
            "demand": item("verb/noun", "强烈要求；需求", "ask forcefully or create a strong need for something", "强调强势要求，或市场/任务带来的高需求。", ["demand an explanation", "demand that", "in high demand"], "正式、商业和冲突语境常见，语气较强。", "礼貌请求不要轻易用 demand。", "The public demanded a transparent investigation.", "公众强烈要求进行透明的调查。"),
        },
    ),
)
